### ISSUE TITLE
Support specifying channels and series type in 'archive' 

### ISSUE THREAD

**Issue by skottmckay** [bergos/fronius#10]
Hi. I'm using your excellent module with Blynk and wanted to capture the daily total kWH produced. I found I can do this via the archive endpoint but need a couple of things exposed for it to be usable. 

Is it possible to make the Channel and SeriesType values configurable? 

```  
async archive ({ start, end, channel_list = channels, series_type = 'Detail',  scope = 'System', format = 'json' }) {
    const query = {
      Scope: scope,
      StartDate: start.toISOString(),
      EndDate: end.toISOString(),
      Channel: channel_list,
      SeriesType: series_type,
      HumanReadable: 'False'
    }
```

Example usage to get today's production:
```
    var now = new Date()
    var begin_today = new Date()
    begin_today.setHours(0, 0, 0, 0)
    
    client.archive({start: begin_today, end: now, series_type: 'DailySum', channel_list:['EnergyReal_WAC_Sum_Produced']}).then(data => {
        var kWH_today = parseFloat(data[0]['energyOutgoing']) / 1000;
        console.log('Wh today:', kWH_today.toFixed(3));
    });
```

Side question: If 'scope' is set to 'Device' doesn't DeviceClass and DeviceId also need to be settable, or is there some way to do that I'm missing?

**Comment by bergos** [comment]
I transfer the data to triplestore and run my query there for performance reasons. That's why I did need that feature yet. But the goal of the library is to support all kinds of API calls.

Please try [this](https://github.com/bergos/fronius/tree/ext-archive-interface) branch. The following code gives me the numbers you are looking for:

```javascript
const Client = require('fronius/Client.js')

async function main () {
  const client = new Client('http://.../')

  const result = await client.archive({
    start: new Date('2021-08-20T00:00:00Z'),
    end: new Date('2021-08-21T00:00:00Z'),
    scope: 'Device',
    deviceClass: 'Inverter',
    deviceId: '1',
    seriesType: 'DailySum',
    format: 'raw'
  })

  console.log(result.Body.Data['inverter/1'].Data.EnergyReal_WAC_Sum_Consumed.Values[0])
  console.log(result.Body.Data['inverter/1'].Data.EnergyReal_WAC_Sum_Produced.Values[0])
}

main()

```

The raw format is required cause the more user-friendly json format may need an update to handle daily sums. I will have a look in the following days. Depending on how much work it is, I decide if I make a single or separate release for that fix.

**Comment by skottmckay** [comment]
Threw me for a bit as my inverter only has 'produced' and not 'consumed' data so I was getting an error from the first console.log statement. Works nicely with raw and json data, and with specifying just the one channel.

Thanks!

**Comment by bergos** [comment]
The changes are included in the latest release.
